# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'psych'
gem 'tty-prompt'
gem 'tty-font'
gem 'pastel'
gem 'rspec'
